### ISSUE TITLE
Suporte para Linux!!!!

### ISSUE THREAD

**Issue by Mikael-R** [abnerfs/onetime-file-share#2]
![tux](https://user-images.githubusercontent.com/60241602/80391172-c4ad3380-8883-11ea-981b-4d3a9aa39a98.jpeg)

Por que não?

**Comment by abnerfs** [comment]
Em teoria funciona, não usei nenhum package específico de windows mas não tive a oportunidade de testar no Linux, se você puder testar e me passar em caso de erro eu efetuo a correção, 😉

**Comment by Mikael-R** [comment]
![fshare-erro](https://user-images.githubusercontent.com/60241602/80426760-bc251f00-88bc-11ea-9574-8e2a75b9b301.png)
Instalei pelo npm, apareceu esse erro.

**Comment by abnerfs** [comment]
Isso é erro padrão de permissão do linux, faltou um sudo

```
sudo npm install onetime-file-share
```

😉

**Comment by Mikael-R** [comment]
Eu acho que esse comando da print eu executei com sudo, mas eu tentei novamente *COM SUDO* e apareceu o mesmo erro

**Comment by abnerfs** [comment]
@Mikael-R vou testar em uma VM Linux pra reproduzir o erro

**Comment by abnerfs** [comment]
@Mikael-R  eu dei uma testada e parece ser um problema com a dependência do ngrok, tenta o comando.

```
sudo npm i -g onetime-file-share --unsafe-perm=true --allow-root
```

eu testei no meu Raspberry Pi e funcionou, se der certo pra você vou atualizar no readme

![2020-04-27-215048_1280x720_scrot](https://user-images.githubusercontent.com/14078661/80434862-52fbd680-88d1-11ea-8037-2511d39f64ad.png)

**Comment by Mikael-R** [comment]
Está funcionando, parabéns.

Só mais uma dúvida, eu consigo upar arquivos até o tamanho que eu quiser?

**Comment by abnerfs** [comment]
Em teoria sim, mas a experiência é melhor com arquivos pequenos, arquivos grandes provavelmente vai demorar bastante pra transferir por conta do ngrok
